logFormat = "Terminal" # one of: Text | Json | Terminal
logLevel = "Debug" #	one of: "Info" # Trace | Info | Debug | Warn | Error | Fatal
sleepPeriod = 10 # sleep period in seconds

[database]
# connections configuration
server = "localhost" # set by environment variables
user = "lw" # set by environment variables
password = "lw" # set by environment variables
database = "stock" # set by environment variables
verbose = false

[connectionPool]
maxPoolSize = 1
maxIdleConnections = 1
maxLifetimeSeconds = 0

[sage]
endpoint = "https://157.231.105.106:40027/api"
authToken="ngEXJVHb4mHYvr2tuNTsjBNz"
productEndpoint = "/product/"